import type { Rep } from "./types";

/**
 * ~45 realistic D2D sales reps for demo / fallback mode.
 * Used when the live AMPA API returns fewer than 5 valid reps or contains
 * junk/test names.
 */
export const MOCK_REPS: Rep[] = [
  /* ------------------------------------------------------------------ */
  /* PEST CONTROL — Team Lead: Marcus Webb (rep-001)                     */
  /* ------------------------------------------------------------------ */
  {
    id: "rep-001",
    first_name: "Marcus",
    last_name: "Webb",
    full_name: "Marcus Webb",
    initials: "MW",
    vertical: "pest",
    onboarding_step: "complete",
    health: "green",
    phone: "+15552010001",
    email: "marcus.webb@example.com",
    address: "412 Oakwood Dr, Phoenix, AZ 85001",
    onboarded_at: "2026-01-15T10:00:00Z",
    created_at: "2025-11-01T09:00:00Z",
    last_activity_at: "2026-06-17T14:22:00Z",
    level_of_experience: "veteran",
    google_calendar_connected: true,
    microsoft_calendar_connected: false,
    direct_recruiter: null,
  },
  {
    id: "rep-004",
    first_name: "Devon",
    last_name: "Banks",
    full_name: "Devon Banks",
    initials: "DB",
    vertical: "pest",
    onboarding_step: "complete",
    health: "green",
    phone: "+15552010004",
    email: "devon.banks@example.com",
    address: "88 Cactus Rd, Mesa, AZ 85201",
    onboarded_at: "2026-02-10T09:00:00Z",
    created_at: "2025-12-01T09:00:00Z",
    last_activity_at: "2026-06-16T11:05:00Z",
    level_of_experience: "experienced",
    google_calendar_connected: true,
    microsoft_calendar_connected: false,
    direct_recruiter: "rep-001",
  },
  {
    id: "rep-005",
    first_name: "Chase",
    last_name: "Morales",
    full_name: "Chase Morales",
    initials: "CM",
    vertical: "pest",
    onboarding_step: "in_progress",
    health: "yellow",
    phone: "+15552010005",
    email: "chase.morales@example.com",
    address: "213 Desert View Blvd, Scottsdale, AZ 85251",
    onboarded_at: null,
    created_at: "2026-01-15T09:00:00Z",
    last_activity_at: "2026-06-08T16:33:00Z",
    level_of_experience: "experienced",
    google_calendar_connected: false,
    microsoft_calendar_connected: false,
    direct_recruiter: "rep-001",
  },
  {
    id: "rep-006",
    first_name: "Kayla",
    last_name: "Simmons",
    full_name: "Kayla Simmons",
    initials: "KS",
    vertical: "pest",
    onboarding_step: "in_progress",
    health: "yellow",
    phone: "+15552010006",
    email: "kayla.simmons@example.com",
    address: "750 Saguaro St, Tempe, AZ 85281",
    onboarded_at: null,
    created_at: "2026-02-20T09:00:00Z",
    last_activity_at: "2026-06-05T09:14:00Z",
    level_of_experience: "rookie",
    google_calendar_connected: false,
    microsoft_calendar_connected: false,
    direct_recruiter: "rep-001",
  },
  {
    id: "rep-007",
    first_name: "Brittany",
    last_name: "Hayes",
    full_name: "Brittany Hayes",
    initials: "BH",
    vertical: "pest",
    onboarding_step: "not_started",
    health: "red",
    phone: "+15552010007",
    email: "brittany.hayes@example.com",
    address: "301 Palo Verde Ave, Chandler, AZ 85224",
    onboarded_at: null,
    created_at: "2026-03-10T09:00:00Z",
    last_activity_at: "2026-05-20T08:00:00Z",
    level_of_experience: "rookie",
    google_calendar_connected: false,
    microsoft_calendar_connected: false,
    direct_recruiter: "rep-001",
  },
  {
    id: "rep-026",
    first_name: "Darius",
    last_name: "Hill",
    full_name: "Darius Hill",
    initials: "DH",
    vertical: "pest",
    onboarding_step: "complete",
    health: "green",
    phone: "+15553010026",
    email: "darius.hill@example.com",
    address: "1021 Sunflower Dr, Phoenix, AZ 85012",
    onboarded_at: "2026-03-20T10:00:00Z",
    created_at: "2026-01-10T09:00:00Z",
    last_activity_at: "2026-06-17T09:30:00Z",
    level_of_experience: "experienced",
    google_calendar_connected: true,
    microsoft_calendar_connected: false,
    direct_recruiter: "rep-001",
  },
  {
    id: "rep-027",
    first_name: "Trey",
    last_name: "Simmons",
    full_name: "Trey Simmons",
    initials: "TS",
    vertical: "pest",
    onboarding_step: "complete",
    health: "green",
    phone: "+15553010027",
    email: "trey.simmons@example.com",
    address: "549 Cholla Blvd, Glendale, AZ 85305",
    onboarded_at: "2026-02-15T10:00:00Z",
    created_at: "2025-12-05T09:00:00Z",
    last_activity_at: "2026-06-15T13:10:00Z",
    level_of_experience: "veteran",
    google_calendar_connected: true,
    microsoft_calendar_connected: false,
    direct_recruiter: null,
  },
  {
    id: "rep-028",
    first_name: "Savannah",
    last_name: "Mitchell",
    full_name: "Savannah Mitchell",
    initials: "SM",
    vertical: "pest",
    onboarding_step: "in_progress",
    health: "yellow",
    phone: "+15553010028",
    email: "savannah.mitchell@example.com",
    address: "204 Mesquite Ln, Scottsdale, AZ 85255",
    onboarded_at: null,
    created_at: "2026-02-28T09:00:00Z",
    last_activity_at: "2026-06-04T15:00:00Z",
    level_of_experience: "rookie",
    google_calendar_connected: false,
    microsoft_calendar_connected: false,
    direct_recruiter: "rep-027",
  },
  {
    id: "rep-029",
    first_name: "Paige",
    last_name: "Turner",
    full_name: "Paige Turner",
    initials: "PT",
    vertical: "pest",
    onboarding_step: "not_started",
    health: "red",
    phone: "+15553010029",
    email: "paige.turner@example.com",
    address: "876 Ironwood Ct, Mesa, AZ 85207",
    onboarded_at: null,
    created_at: "2026-04-01T09:00:00Z",
    last_activity_at: "2026-05-15T10:00:00Z",
    level_of_experience: "rookie",
    google_calendar_connected: false,
    microsoft_calendar_connected: false,
    direct_recruiter: "rep-027",
  },
  {
    id: "rep-030",
    first_name: "Ciara",
    last_name: "Nguyen",
    full_name: "Ciara Nguyen",
    initials: "CN",
    vertical: "pest",
    onboarding_step: "complete",
    health: "green",
    phone: "+15553010030",
    email: "ciara.nguyen@example.com",
    address: "333 Agave Way, Tempe, AZ 85282",
    onboarded_at: "2026-04-10T10:00:00Z",
    created_at: "2026-02-15T09:00:00Z",
    last_activity_at: "2026-06-16T08:45:00Z",
    level_of_experience: "experienced",
    google_calendar_connected: false,
    microsoft_calendar_connected: false,
    direct_recruiter: "rep-027",
  },
  {
    id: "rep-031",
    first_name: "Destiny",
    last_name: "Adams",
    full_name: "Destiny Adams",
    initials: "DA",
    vertical: "pest",
    onboarding_step: "in_progress",
    health: "yellow",
    phone: "+15553010031",
    email: "destiny.adams@example.com",
    address: "614 Catalina Ct, Chandler, AZ 85225",
    onboarded_at: null,
    created_at: "2026-03-05T09:00:00Z",
    last_activity_at: "2026-06-06T11:20:00Z",
    level_of_experience: "rookie",
    google_calendar_connected: false,
    microsoft_calendar_connected: false,
    direct_recruiter: "rep-001",
  },
  /* ------------------------------------------------------------------ */
  /* LIFE INSURANCE — Team Lead: Jordan Fields (rep-002)                  */
  /* ------------------------------------------------------------------ */
  {
    id: "rep-002",
    first_name: "Jordan",
    last_name: "Fields",
    full_name: "Jordan Fields",
    initials: "JF",
    vertical: "life_insurance",
    onboarding_step: "complete",
    health: "green",
    phone: "+15552010002",
    email: "jordan.fields@example.com",
    address: "1020 Liberty Ln, Gilbert, AZ 85234",
    onboarded_at: "2025-12-10T10:00:00Z",
    created_at: "2025-09-01T09:00:00Z",
    last_activity_at: "2026-06-18T08:45:00Z",
    level_of_experience: "veteran",
    google_calendar_connected: true,
    microsoft_calendar_connected: true,
    direct_recruiter: null,
  },
  {
    id: "rep-013",
    first_name: "Caleb",
    last_name: "Foster",
    full_name: "Caleb Foster",
    initials: "CF",
    vertical: "life_insurance",
    onboarding_step: "complete",
    health: "green",
    phone: "+15552010013",
    email: "caleb.foster@example.com",
    address: "504 Ironwood Ct, Peoria, AZ 85381",
    onboarded_at: "2026-02-28T10:00:00Z",
    created_at: "2025-12-15T09:00:00Z",
    last_activity_at: "2026-06-15T13:55:00Z",
    level_of_experience: "experienced",
    google_calendar_connected: true,
    microsoft_calendar_connected: false,
    direct_recruiter: "rep-002",
  },
  {
    id: "rep-014",
    first_name: "Nathan",
    last_name: "Briggs",
    full_name: "Nathan Briggs",
    initials: "NB",
    vertical: "life_insurance",
    onboarding_step: "in_progress",
    health: "yellow",
    phone: "+15552010014",
    email: "nathan.briggs@example.com",
    address: "67 Elm Park Way, Surprise, AZ 85374",
    onboarded_at: null,
    created_at: "2026-01-20T09:00:00Z",
    last_activity_at: "2026-06-10T10:30:00Z",
    level_of_experience: "experienced",
    google_calendar_connected: false,
    microsoft_calendar_connected: false,
    direct_recruiter: "rep-002",
  },
  {
    id: "rep-015",
    first_name: "Austin",
    last_name: "Reed",
    full_name: "Austin Reed",
    initials: "AR",
    vertical: "life_insurance",
    onboarding_step: "in_progress",
    health: "yellow",
    phone: "+15552010015",
    email: "austin.reed@example.com",
    address: "192 Sonoran Blvd, Avondale, AZ 85323",
    onboarded_at: null,
    created_at: "2026-02-05T09:00:00Z",
    last_activity_at: "2026-06-03T15:00:00Z",
    level_of_experience: "rookie",
    google_calendar_connected: false,
    microsoft_calendar_connected: false,
    direct_recruiter: "rep-002",
  },
  {
    id: "rep-016",
    first_name: "Eli",
    last_name: "Carpenter",
    full_name: "Eli Carpenter",
    initials: "EC",
    vertical: "life_insurance",
    onboarding_step: "not_started",
    health: "red",
    phone: "+15552010016",
    email: "eli.carpenter@example.com",
    address: "830 Quail Run Dr, Glendale, AZ 85301",
    onboarded_at: null,
    created_at: "2026-03-01T09:00:00Z",
    last_activity_at: "2026-05-22T09:00:00Z",
    level_of_experience: "rookie",
    google_calendar_connected: false,
    microsoft_calendar_connected: false,
    direct_recruiter: "rep-002",
  },
  {
    id: "rep-032",
    first_name: "Marcus",
    last_name: "Cole",
    full_name: "Marcus Cole",
    initials: "MC",
    vertical: "life_insurance",
    onboarding_step: "complete",
    health: "green",
    phone: "+15553010032",
    email: "marcus.cole@example.com",
    address: "720 Buckeye Rd, Phoenix, AZ 85003",
    onboarded_at: "2026-03-01T10:00:00Z",
    created_at: "2026-01-05T09:00:00Z",
    last_activity_at: "2026-06-18T07:55:00Z",
    level_of_experience: "experienced",
    google_calendar_connected: true,
    microsoft_calendar_connected: false,
    direct_recruiter: "rep-002",
  },
  {
    id: "rep-033",
    first_name: "Lauren",
    last_name: "Scott",
    full_name: "Lauren Scott",
    initials: "LS",
    vertical: "life_insurance",
    onboarding_step: "complete",
    health: "green",
    phone: "+15553010033",
    email: "lauren.scott@example.com",
    address: "98 Palm Canyon Dr, Surprise, AZ 85379",
    onboarded_at: "2026-04-05T10:00:00Z",
    created_at: "2026-02-10T09:00:00Z",
    last_activity_at: "2026-06-17T16:20:00Z",
    level_of_experience: "veteran",
    google_calendar_connected: true,
    microsoft_calendar_connected: true,
    direct_recruiter: null,
  },
  {
    id: "rep-034",
    first_name: "Priya",
    last_name: "Patel",
    full_name: "Priya Patel",
    initials: "PP",
    vertical: "life_insurance",
    onboarding_step: "not_started",
    health: "red",
    phone: "+15553010034",
    email: "priya.patel@example.com",
    address: "410 Greenway Pkwy, Peoria, AZ 85382",
    onboarded_at: null,
    created_at: "2026-04-15T09:00:00Z",
    last_activity_at: "2026-05-28T09:00:00Z",
    level_of_experience: "rookie",
    google_calendar_connected: false,
    microsoft_calendar_connected: false,
    direct_recruiter: "rep-033",
  },
  /* ------------------------------------------------------------------ */
  /* ALARMS — Team Lead: Tyler Nguyen (rep-003)                          */
  /* ------------------------------------------------------------------ */
  {
    id: "rep-003",
    first_name: "Tyler",
    last_name: "Nguyen",
    full_name: "Tyler Nguyen",
    initials: "TN",
    vertical: "alarms",
    onboarding_step: "complete",
    health: "green",
    phone: "+15552010003",
    email: "tyler.nguyen@example.com",
    address: "2200 Camelback Rd, Phoenix, AZ 85016",
    onboarded_at: "2025-11-20T10:00:00Z",
    created_at: "2025-08-15T09:00:00Z",
    last_activity_at: "2026-06-17T17:00:00Z",
    level_of_experience: "veteran",
    google_calendar_connected: true,
    microsoft_calendar_connected: false,
    direct_recruiter: null,
  },
  {
    id: "rep-017",
    first_name: "Zach",
    last_name: "Morrison",
    full_name: "Zach Morrison",
    initials: "ZM",
    vertical: "alarms",
    onboarding_step: "complete",
    health: "green",
    phone: "+15552010017",
    email: "zach.morrison@example.com",
    address: "109 Copper Canyon Ct, Buckeye, AZ 85326",
    onboarded_at: "2026-01-30T10:00:00Z",
    created_at: "2025-11-10T09:00:00Z",
    last_activity_at: "2026-06-14T10:00:00Z",
    level_of_experience: "experienced",
    google_calendar_connected: true,
    microsoft_calendar_connected: false,
    direct_recruiter: "rep-003",
  },
  {
    id: "rep-018",
    first_name: "Samantha",
    last_name: "Price",
    full_name: "Samantha Price",
    initials: "SP",
    vertical: "alarms",
    onboarding_step: "complete",
    health: "green",
    phone: "+15552010018",
    email: "samantha.price@example.com",
    address: "45 Sunridge Dr, Casa Grande, AZ 85122",
    onboarded_at: "2025-10-05T10:00:00Z",
    created_at: "2025-07-01T09:00:00Z",
    last_activity_at: "2026-06-16T14:30:00Z",
    level_of_experience: "veteran",
    google_calendar_connected: true,
    microsoft_calendar_connected: true,
    direct_recruiter: "rep-003",
  },
  {
    id: "rep-019",
    first_name: "Danielle",
    last_name: "Owens",
    full_name: "Danielle Owens",
    initials: "DO",
    vertical: "alarms",
    onboarding_step: "in_progress",
    health: "yellow",
    phone: "+15552010019",
    email: "danielle.owens@example.com",
    address: "378 Maricopa Hwy, Maricopa, AZ 85138",
    onboarded_at: null,
    created_at: "2026-01-10T09:00:00Z",
    last_activity_at: "2026-06-07T11:22:00Z",
    level_of_experience: "experienced",
    google_calendar_connected: false,
    microsoft_calendar_connected: false,
    direct_recruiter: "rep-003",
  },
  {
    id: "rep-020",
    first_name: "Rachel",
    last_name: "Kim",
    full_name: "Rachel Kim",
    initials: "RK",
    vertical: "alarms",
    onboarding_step: "not_started",
    health: "red",
    phone: "+15552010020",
    email: "rachel.kim@example.com",
    address: "617 Greenfield Rd, Gilbert, AZ 85297",
    onboarded_at: null,
    created_at: "2026-03-15T09:00:00Z",
    last_activity_at: "2026-05-25T08:30:00Z",
    level_of_experience: "rookie",
    google_calendar_connected: false,
    microsoft_calendar_connected: false,
    direct_recruiter: "rep-003",
  },
  {
    id: "rep-035",
    first_name: "Jordan",
    last_name: "West",
    full_name: "Jordan West",
    initials: "JW",
    vertical: "alarms",
    onboarding_step: "complete",
    health: "green",
    phone: "+15553010035",
    email: "jordan.west@example.com",
    address: "512 Estrella Dr, Avondale, AZ 85323",
    onboarded_at: "2026-03-10T10:00:00Z",
    created_at: "2026-01-20T09:00:00Z",
    last_activity_at: "2026-06-16T15:00:00Z",
    level_of_experience: "experienced",
    google_calendar_connected: true,
    microsoft_calendar_connected: false,
    direct_recruiter: "rep-003",
  },
  {
    id: "rep-036",
    first_name: "Cody",
    last_name: "Barnes",
    full_name: "Cody Barnes",
    initials: "CB",
    vertical: "alarms",
    onboarding_step: "in_progress",
    health: "yellow",
    phone: "+15553010036",
    email: "cody.barnes@example.com",
    address: "189 Desert Rose Ln, Goodyear, AZ 85338",
    onboarded_at: null,
    created_at: "2026-03-01T09:00:00Z",
    last_activity_at: "2026-06-09T09:00:00Z",
    level_of_experience: "rookie",
    google_calendar_connected: false,
    microsoft_calendar_connected: false,
    direct_recruiter: "rep-003",
  },
  {
    id: "rep-037",
    first_name: "Maya",
    last_name: "Freeman",
    full_name: "Maya Freeman",
    initials: "MF",
    vertical: "alarms",
    onboarding_step: "not_started",
    health: "red",
    phone: "+15553010037",
    email: "maya.freeman@example.com",
    address: "701 Quartz Way, Surprise, AZ 85374",
    onboarded_at: null,
    created_at: "2026-04-10T09:00:00Z",
    last_activity_at: "2026-05-18T08:00:00Z",
    level_of_experience: "rookie",
    google_calendar_connected: false,
    microsoft_calendar_connected: false,
    direct_recruiter: "rep-035",
  },
  /* ------------------------------------------------------------------ */
  /* SOLAR — Team Lead: Jasmine Torres (rep-008)                         */
  /* ------------------------------------------------------------------ */
  {
    id: "rep-008",
    first_name: "Jasmine",
    last_name: "Torres",
    full_name: "Jasmine Torres",
    initials: "JT",
    vertical: "solar",
    onboarding_step: "complete",
    health: "green",
    phone: "+15552010008",
    email: "jasmine.torres@example.com",
    address: "900 Sunburst Dr, Scottsdale, AZ 85260",
    onboarded_at: "2025-12-01T10:00:00Z",
    created_at: "2025-09-15T09:00:00Z",
    last_activity_at: "2026-06-18T09:10:00Z",
    level_of_experience: "veteran",
    google_calendar_connected: true,
    microsoft_calendar_connected: false,
    direct_recruiter: null,
  },
  {
    id: "rep-009",
    first_name: "Alexis",
    last_name: "Rivera",
    full_name: "Alexis Rivera",
    initials: "AR",
    vertical: "solar",
    onboarding_step: "complete",
    health: "green",
    phone: "+15552010009",
    email: "alexis.rivera@example.com",
    address: "1140 Villa Nueva Way, Tempe, AZ 85284",
    onboarded_at: "2026-02-14T10:00:00Z",
    created_at: "2025-12-10T09:00:00Z",
    last_activity_at: "2026-06-13T12:45:00Z",
    level_of_experience: "experienced",
    google_calendar_connected: false,
    microsoft_calendar_connected: false,
    direct_recruiter: "rep-008",
  },
  {
    id: "rep-010",
    first_name: "Tiffany",
    last_name: "Brooks",
    full_name: "Tiffany Brooks",
    initials: "TB",
    vertical: "solar",
    onboarding_step: "in_progress",
    health: "yellow",
    phone: "+15552010010",
    email: "tiffany.brooks@example.com",
    address: "52 Mango Terrace, Mesa, AZ 85205",
    onboarded_at: null,
    created_at: "2026-01-25T09:00:00Z",
    last_activity_at: "2026-06-09T14:00:00Z",
    level_of_experience: "experienced",
    google_calendar_connected: false,
    microsoft_calendar_connected: false,
    direct_recruiter: "rep-008",
  },
  {
    id: "rep-011",
    first_name: "Ashley",
    last_name: "Diaz",
    full_name: "Ashley Diaz",
    initials: "AD",
    vertical: "solar",
    onboarding_step: "in_progress",
    health: "yellow",
    phone: "+15552010011",
    email: "ashley.diaz@example.com",
    address: "730 Adobe Hills Rd, Goodyear, AZ 85338",
    onboarded_at: null,
    created_at: "2026-02-18T09:00:00Z",
    last_activity_at: "2026-06-04T10:15:00Z",
    level_of_experience: "rookie",
    google_calendar_connected: false,
    microsoft_calendar_connected: false,
    direct_recruiter: "rep-008",
  },
  {
    id: "rep-012",
    first_name: "Brandon",
    last_name: "Clark",
    full_name: "Brandon Clark",
    initials: "BC",
    vertical: "solar",
    onboarding_step: "not_started",
    health: "red",
    phone: "+15552010012",
    email: "brandon.clark@example.com",
    address: "280 Westgate Blvd, Litchfield Park, AZ 85340",
    onboarded_at: null,
    created_at: "2026-03-20T09:00:00Z",
    last_activity_at: "2026-05-19T09:00:00Z",
    level_of_experience: "rookie",
    google_calendar_connected: false,
    microsoft_calendar_connected: false,
    direct_recruiter: "rep-008",
  },
  {
    id: "rep-038",
    first_name: "Trevor",
    last_name: "Walsh",
    full_name: "Trevor Walsh",
    initials: "TW",
    vertical: "solar",
    onboarding_step: "complete",
    health: "green",
    phone: "+15553010038",
    email: "trevor.walsh@example.com",
    address: "1350 Solar Park Blvd, Chandler, AZ 85248",
    onboarded_at: "2026-02-20T10:00:00Z",
    created_at: "2025-12-18T09:00:00Z",
    last_activity_at: "2026-06-17T10:00:00Z",
    level_of_experience: "veteran",
    google_calendar_connected: true,
    microsoft_calendar_connected: false,
    direct_recruiter: null,
  },
  {
    id: "rep-039",
    first_name: "Garrett",
    last_name: "Holt",
    full_name: "Garrett Holt",
    initials: "GH",
    vertical: "solar",
    onboarding_step: "complete",
    health: "green",
    phone: "+15553010039",
    email: "garrett.holt@example.com",
    address: "775 Copper Mine Rd, Gilbert, AZ 85296",
    onboarded_at: "2026-03-18T10:00:00Z",
    created_at: "2026-01-22T09:00:00Z",
    last_activity_at: "2026-06-15T11:30:00Z",
    level_of_experience: "experienced",
    google_calendar_connected: false,
    microsoft_calendar_connected: false,
    direct_recruiter: "rep-038",
  },
  {
    id: "rep-040",
    first_name: "Aaliyah",
    last_name: "Grant",
    full_name: "Aaliyah Grant",
    initials: "AG",
    vertical: "solar",
    onboarding_step: "in_progress",
    health: "yellow",
    phone: "+15553010040",
    email: "aaliyah.grant@example.com",
    address: "322 Bright Sun Ct, Tempe, AZ 85283",
    onboarded_at: null,
    created_at: "2026-03-10T09:00:00Z",
    last_activity_at: "2026-06-08T12:00:00Z",
    level_of_experience: "rookie",
    google_calendar_connected: false,
    microsoft_calendar_connected: false,
    direct_recruiter: "rep-038",
  },
  {
    id: "rep-041",
    first_name: "Vanessa",
    last_name: "Cruz",
    full_name: "Vanessa Cruz",
    initials: "VC",
    vertical: "solar",
    onboarding_step: "not_started",
    health: "red",
    phone: "+15553010041",
    email: "vanessa.cruz@example.com",
    address: "554 Desert Hawk Dr, Mesa, AZ 85208",
    onboarded_at: null,
    created_at: "2026-04-05T09:00:00Z",
    last_activity_at: "2026-05-22T09:00:00Z",
    level_of_experience: "rookie",
    google_calendar_connected: false,
    microsoft_calendar_connected: false,
    direct_recruiter: "rep-008",
  },
  /* ------------------------------------------------------------------ */
  /* FIBER — Team Leads: Mia Chen (rep-021), Derek Stone (rep-022)       */
  /* ------------------------------------------------------------------ */
  {
    id: "rep-021",
    first_name: "Mia",
    last_name: "Chen",
    full_name: "Mia Chen",
    initials: "MC",
    vertical: "fiber",
    onboarding_step: "complete",
    health: "green",
    phone: "+15552010021",
    email: "mia.chen@example.com",
    address: "1500 Pinnacle Peak Rd, Phoenix, AZ 85027",
    onboarded_at: "2026-03-01T10:00:00Z",
    created_at: "2025-12-20T09:00:00Z",
    last_activity_at: "2026-06-17T11:30:00Z",
    level_of_experience: "experienced",
    google_calendar_connected: true,
    microsoft_calendar_connected: false,
    direct_recruiter: null,
  },
  {
    id: "rep-022",
    first_name: "Derek",
    last_name: "Stone",
    full_name: "Derek Stone",
    initials: "DS",
    vertical: "fiber",
    onboarding_step: "complete",
    health: "green",
    phone: "+15552010022",
    email: "derek.stone@example.com",
    address: "614 Ridgeline Ct, Chandler, AZ 85249",
    onboarded_at: "2025-10-20T10:00:00Z",
    created_at: "2025-07-15T09:00:00Z",
    last_activity_at: "2026-06-16T16:00:00Z",
    level_of_experience: "veteran",
    google_calendar_connected: true,
    microsoft_calendar_connected: true,
    direct_recruiter: null,
  },
  {
    id: "rep-023",
    first_name: "Justin",
    last_name: "Lawson",
    full_name: "Justin Lawson",
    initials: "JL",
    vertical: "fiber",
    onboarding_step: "complete",
    health: "green",
    phone: "+15552010023",
    email: "justin.lawson@example.com",
    address: "337 Mesquite Hollow Dr, Gilbert, AZ 85295",
    onboarded_at: "2026-01-05T10:00:00Z",
    created_at: "2025-10-01T09:00:00Z",
    last_activity_at: "2026-06-12T08:50:00Z",
    level_of_experience: "experienced",
    google_calendar_connected: false,
    microsoft_calendar_connected: false,
    direct_recruiter: null,
  },
  {
    id: "rep-024",
    first_name: "Ryan",
    last_name: "Ortega",
    full_name: "Ryan Ortega",
    initials: "RO",
    vertical: "fiber",
    onboarding_step: "in_progress",
    health: "yellow",
    phone: "+15552010024",
    email: "ryan.ortega@example.com",
    address: "488 Ironwood Pass, Queen Creek, AZ 85142",
    onboarded_at: null,
    created_at: "2026-02-01T09:00:00Z",
    last_activity_at: "2026-06-02T12:00:00Z",
    level_of_experience: "experienced",
    google_calendar_connected: false,
    microsoft_calendar_connected: false,
    direct_recruiter: null,
  },
  {
    id: "rep-025",
    first_name: "Kyle",
    last_name: "Patterson",
    full_name: "Kyle Patterson",
    initials: "KP",
    vertical: "fiber",
    onboarding_step: "not_started",
    health: "red",
    phone: "+15552010025",
    email: "kyle.patterson@example.com",
    address: "925 Estrella Pkwy, Goodyear, AZ 85338",
    onboarded_at: null,
    created_at: "2026-03-25T09:00:00Z",
    last_activity_at: "2026-05-18T10:00:00Z",
    level_of_experience: "rookie",
    google_calendar_connected: false,
    microsoft_calendar_connected: false,
    direct_recruiter: null,
  },
  {
    id: "rep-042",
    first_name: "Spencer",
    last_name: "Lane",
    full_name: "Spencer Lane",
    initials: "SL",
    vertical: "fiber",
    onboarding_step: "complete",
    health: "green",
    phone: "+15553010042",
    email: "spencer.lane@example.com",
    address: "840 Fiber Ct, Peoria, AZ 85383",
    onboarded_at: "2026-04-01T10:00:00Z",
    created_at: "2026-02-05T09:00:00Z",
    last_activity_at: "2026-06-17T14:00:00Z",
    level_of_experience: "experienced",
    google_calendar_connected: true,
    microsoft_calendar_connected: false,
    direct_recruiter: "rep-022",
  },
  {
    id: "rep-043",
    first_name: "Blake",
    last_name: "Fowler",
    full_name: "Blake Fowler",
    initials: "BF",
    vertical: "fiber",
    onboarding_step: "complete",
    health: "green",
    phone: "+15553010043",
    email: "blake.fowler@example.com",
    address: "263 Bandwidth Blvd, Gilbert, AZ 85234",
    onboarded_at: "2026-01-20T10:00:00Z",
    created_at: "2025-11-15T09:00:00Z",
    last_activity_at: "2026-06-16T10:30:00Z",
    level_of_experience: "veteran",
    google_calendar_connected: true,
    microsoft_calendar_connected: true,
    direct_recruiter: null,
  },
  {
    id: "rep-044",
    first_name: "Colton",
    last_name: "Reid",
    full_name: "Colton Reid",
    initials: "CR",
    vertical: "fiber",
    onboarding_step: "in_progress",
    health: "yellow",
    phone: "+15553010044",
    email: "colton.reid@example.com",
    address: "417 Network Way, Chandler, AZ 85225",
    onboarded_at: null,
    created_at: "2026-02-20T09:00:00Z",
    last_activity_at: "2026-06-07T13:45:00Z",
    level_of_experience: "experienced",
    google_calendar_connected: false,
    microsoft_calendar_connected: false,
    direct_recruiter: "rep-043",
  },
  {
    id: "rep-045",
    first_name: "Destiny",
    last_name: "Cook",
    full_name: "Destiny Cook",
    initials: "DC",
    vertical: "fiber",
    onboarding_step: "not_started",
    health: "red",
    phone: "+15553010045",
    email: "destiny.cook@example.com",
    address: "558 Signal Hill Dr, Scottsdale, AZ 85254",
    onboarded_at: null,
    created_at: "2026-04-20T09:00:00Z",
    last_activity_at: "2026-05-16T11:00:00Z",
    level_of_experience: "rookie",
    google_calendar_connected: false,
    microsoft_calendar_connected: false,
    direct_recruiter: "rep-021",
  },
];
